# typed: false
# frozen_string_literal: true

# This file is generated by scripts/update-formula.sh. Do not edit by hand.
class Odiff < Formula
  desc "The fastest pixel-by-pixel image visual-difference tool"
  homepage "https://github.com/dmtrKovalenko/odiff"
  version "4.5.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/dmtrKovalenko/odiff/releases/download/v4.5.0/odiff-macos-x64"
      sha256 "73e565e2a777b653fa0ceb90c138dec1c396c990913fdc1221fe8b01fa70c171"
    end
    on_arm do
      url "https://github.com/dmtrKovalenko/odiff/releases/download/v4.5.0/odiff-macos-arm64"
      sha256 "3c681171c158f95e7e62d636ddd00c33e8f971c23c85239c6192b72d76ad665b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dmtrKovalenko/odiff/releases/download/v4.5.0/odiff-linux-x64"
      sha256 "2eb5a7f44df925d93b451898de8bf213f0aac270a9781187746097ed7cd45324"
    end
    on_arm do
      url "https://github.com/dmtrKovalenko/odiff/releases/download/v4.5.0/odiff-linux-arm64"
      sha256 "245ad45851da200cfdd361374618fca22781919faaca255aed1c93b883beb476"
    end
  end

  def install
    # Each platform downloads a single raw binary named odiff-<os>-<arch>.
    bin.install Dir["odiff-*"].first => "odiff"
  end

  livecheck do
    url :homepage
    strategy :github_latest
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/odiff --version")
  end
end
