# typed: false
# frozen_string_literal: true

# This file is generated by scripts/update-formula.sh. Do not edit by hand.
class Odiff < Formula
  desc "The fastest pixel-by-pixel image visual-difference tool"
  homepage "https://github.com/dmtrKovalenko/odiff"
  version "4.4.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/dmtrKovalenko/odiff/releases/download/v4.4.4/odiff-macos-x64"
      sha256 "97be4fed8e265fe8ea4e531ce8f33a5e2140aee741041f2b0bb71d5e3573f2ca"
    end
    on_arm do
      url "https://github.com/dmtrKovalenko/odiff/releases/download/v4.4.4/odiff-macos-arm64"
      sha256 "613f304d9408bd5fb99d0e678a67d8401b51358631869c596ddb42b3732d0bb1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dmtrKovalenko/odiff/releases/download/v4.4.4/odiff-linux-x64"
      sha256 "4f1768963b9583c0eb764555f1629f164a901fe47317ed581a908b4ddec6eb43"
    end
    on_arm do
      url "https://github.com/dmtrKovalenko/odiff/releases/download/v4.4.4/odiff-linux-arm64"
      sha256 "2b72b9b536d9168106d336526413ea8abad07e422a261b3da2ec1ada4cc15f03"
    end
  end

  def install
    # Each platform downloads a single raw binary named odiff-<os>-<arch>.
    bin.install Dir["odiff-*"].first => "odiff"
  end

  livecheck do
    url :homepage
    strategy :github_latest
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/odiff --version")
  end
end
