# typed: false
# frozen_string_literal: true

# This file is generated by scripts/update-formula.sh. Do not edit by hand.
class Odiff < Formula
  desc "The fastest pixel-by-pixel image visual-difference tool"
  homepage "https://github.com/dmtrKovalenko/odiff"
  version "4.4.3-dev.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/dmtrKovalenko/odiff/releases/download/v4.4.3-dev.2/odiff-macos-x64"
      sha256 "a1c4f2bbf323e0f36d75e47ffa659956b70135f5e53d3d94a835f8d994d08a1a"
    end
    on_arm do
      url "https://github.com/dmtrKovalenko/odiff/releases/download/v4.4.3-dev.2/odiff-macos-arm64"
      sha256 "9f24e660a770703f85bd284087d6491a24f47926645edd201e07b85946157db1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dmtrKovalenko/odiff/releases/download/v4.4.3-dev.2/odiff-linux-x64"
      sha256 "835dab59362edd888c5d8b42d91c9c3e1daf0c3687756cfbc3c7ab14f46bca36"
    end
    on_arm do
      url "https://github.com/dmtrKovalenko/odiff/releases/download/v4.4.3-dev.2/odiff-linux-arm64"
      sha256 "215fff0400c53aad3463130ede41171231ac5548f423f9a524dc208df37ecb42"
    end
  end

  def install
    # Each platform downloads a single raw binary named odiff-<os>-<arch>.
    bin.install Dir["odiff-*"].first => "odiff"
  end

  livecheck do
    url :homepage
    strategy :github_latest
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/odiff --version")
  end
end
