#!/usr/bin/env bash
#
# Regenerates Formula/odiff.rb from the latest stable release of the upstream
# odiff repository. Idempotent: if the formula already points at the latest
# version it exits without making changes.
#
# Requires: gh (GitHub CLI, authenticated), sha256sum, git.
#
set -euo pipefail

UPSTREAM="${UPSTREAM_REPO:-dmtrKovalenko/odiff}"
FORMULA="Formula/odiff.rb"

# The four release assets Homebrew can consume, mapped to formula slots.
ASSET_MACOS_X64="odiff-macos-x64"
ASSET_MACOS_ARM64="odiff-macos-arm64"
ASSET_LINUX_X64="odiff-linux-x64"
ASSET_LINUX_ARM64="odiff-linux-arm64"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

# ---------------------------------------------------------------------------
# 1. Find the latest stable (non-draft, non-prerelease) release.
# ---------------------------------------------------------------------------
tag="$(gh release list --repo "$UPSTREAM" \
  --exclude-drafts --exclude-pre-releases \
  -L 1 --json tagName --jq '.[0].tagName // empty')"

if [ -z "$tag" ]; then
  echo "No stable release found on $UPSTREAM; nothing to do."
  exit 0
fi

version="${tag#v}"
echo "Latest stable release: $tag (version $version)"

# ---------------------------------------------------------------------------
# 2. Bail out early if the formula is already up to date.
# ---------------------------------------------------------------------------
if [ -f "$FORMULA" ] && grep -q "version \"$version\"" "$FORMULA"; then
  echo "Formula already at $version; nothing to do."
  exit 0
fi

# ---------------------------------------------------------------------------
# 3. Download the four binary assets and hash them.
# ---------------------------------------------------------------------------
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

gh release download "$tag" --repo "$UPSTREAM" --dir "$tmp" \
  --pattern "$ASSET_MACOS_X64" \
  --pattern "$ASSET_MACOS_ARM64" \
  --pattern "$ASSET_LINUX_X64" \
  --pattern "$ASSET_LINUX_ARM64" || true

for asset in "$ASSET_MACOS_X64" "$ASSET_MACOS_ARM64" "$ASSET_LINUX_X64" "$ASSET_LINUX_ARM64"; do
  if [ ! -f "$tmp/$asset" ]; then
    echo "Release $tag is missing asset '$asset'."
    echo "This release predates the prebuilt-binary workflow; skipping."
    exit 0
  fi
done

sha() { sha256sum "$tmp/$1" | cut -d' ' -f1; }

sha_macos_x64="$(sha "$ASSET_MACOS_X64")"
sha_macos_arm64="$(sha "$ASSET_MACOS_ARM64")"
sha_linux_x64="$(sha "$ASSET_LINUX_X64")"
sha_linux_arm64="$(sha "$ASSET_LINUX_ARM64")"

base_url="https://github.com/$UPSTREAM/releases/download/$tag"

# ---------------------------------------------------------------------------
# 4. Render the formula.
# ---------------------------------------------------------------------------
mkdir -p "$(dirname "$FORMULA")"
cat > "$FORMULA" <<EOF
# typed: false
# frozen_string_literal: true

# This file is generated by scripts/update-formula.sh. Do not edit by hand.
class Odiff < Formula
  desc "The fastest pixel-by-pixel image visual-difference tool"
  homepage "https://github.com/$UPSTREAM"
  version "$version"
  license "MIT"

  on_macos do
    on_intel do
      url "$base_url/$ASSET_MACOS_X64"
      sha256 "$sha_macos_x64"
    end
    on_arm do
      url "$base_url/$ASSET_MACOS_ARM64"
      sha256 "$sha_macos_arm64"
    end
  end

  on_linux do
    on_intel do
      url "$base_url/$ASSET_LINUX_X64"
      sha256 "$sha_linux_x64"
    end
    on_arm do
      url "$base_url/$ASSET_LINUX_ARM64"
      sha256 "$sha_linux_arm64"
    end
  end

  def install
    # Each platform downloads a single raw binary named odiff-<os>-<arch>.
    bin.install Dir["odiff-*"].first => "odiff"
  end

  livecheck do
    url :homepage
    strategy :github_latest
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/odiff --version")
  end
end
EOF

echo "Wrote $FORMULA for version $version."

# ---------------------------------------------------------------------------
# 5. Commit and push if something actually changed.
# ---------------------------------------------------------------------------
if [ -z "$(git status --porcelain -- "$FORMULA")" ]; then
  echo "No changes to commit."
  exit 0
fi

if [ "${SKIP_COMMIT:-false}" = "true" ]; then
  echo "SKIP_COMMIT=true; leaving changes uncommitted."
  exit 0
fi

git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git add "$FORMULA"
git commit -m "odiff $version"
git push
echo "Committed and pushed odiff $version."
